Downgrade to sqlx 0.7.4 with just the fixes we want, because sqlx 0.8 alpha broke deserializing to serde_json::Value:
```
error: optional sqlx feature `json` required for type JSONB of param #2
   --> /home/at/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/5d6c33e/src/macros/mod.rs:328:9
    |
314 |   macro_rules! query (
    |   ------------------ in this expansion of `sqlx::query!` (#1)
...
328 |           $crate::sqlx_macros::expand_query!(source = $query, args = [$($args)*])
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ in this macro invocation (#2)
    |
   ::: /home/at/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/5d6c33e/sqlx-macros/src/lib.rs:9:1
    |
9   |   pub fn expand_query(input: TokenStream) -> TokenStream {
    |   ------------------------------------------------------ in this expansion of `$crate::sqlx_macros::expand_query!` (#2)
    |
   ::: src/db/google_auth.rs:28:9
    |
28  | /         sqlx::query!(r#"
29  | |             INSERT INTO stash.google_application_secrets (domain_id, secret)
30  | |             VALUES ($1, $2)"#,
31  | |             &self.domain_id, &self.secret
32  | |         ).execute(&mut **transaction).await?;
    | |_________- in this macro invocation (#1)

error: optional sqlx feature `json` required for type JSONB of column #2 ("secret")
   --> /home/at/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/5d6c33e/src/macros/mod.rs:569:9
    |
567 |   macro_rules! query_as (
    |   --------------------- in this expansion of `sqlx::query_as!` (#1)
568 |       ($out_struct:path, $query:expr) => ( {
569 |           $crate::sqlx_macros::expand_query!(record = $out_struct, source = $query)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ in this macro invocation (#2)
    |
   ::: /home/at/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/5d6c33e/sqlx-macros/src/lib.rs:9:1
    |
9   |   pub fn expand_query(input: TokenStream) -> TokenStream {
    |   ------------------------------------------------------ in this expansion of `$crate::sqlx_macros::expand_query!` (#2)
    |
   ::: src/db/google_auth.rs:38:12
    |
38  |           Ok(sqlx::query_as!(GoogleApplicationSecret, r#"
    |  ____________-
39  | |             SELECT domain_id, secret
40  | |             FROM stash.google_application_secrets"#
41  | |         ).fetch_all(&mut **transaction).await?)
    | |_________- in this macro invocation (#1)

error: optional sqlx feature `json` required for type JSONB of column #2 ("secret")
   --> /home/at/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/5d6c33e/src/macros/mod.rs:572:9
    |
567 |   macro_rules! query_as (
    |   --------------------- in this expansion of `sqlx::query_as!` (#1)
...
572 |           $crate::sqlx_macros::expand_query!(record = $out_struct, source = $query, args = [$($args)*])
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ in this macro invocation (#2)
    |
   ::: /home/at/.cargo/git/checkouts/sqlx-f05f33ba4f5c3036/5d6c33e/sqlx-macros/src/lib.rs:9:1
    |
9   |   pub fn expand_query(input: TokenStream) -> TokenStream {
    |   ------------------------------------------------------ in this expansion of `$crate::sqlx_macros::expand_query!` (#2)
    |
   ::: src/db/google_auth.rs:47:12
    |
47  |           Ok(sqlx::query_as!(GoogleApplicationSecret, r#"
    |  ____________-
48  | |             SELECT domain_id, secret
49  | |             FROM stash.google_application_secrets
50  | |             WHERE domain_id = ANY($1)"#, domain_ids
51  | |         ).fetch_all(&mut **transaction).await?)
    | |_________- in this macro invocation (#1)

error: could not compile `exastash` (lib) due to 3 previous errors
```