db: try to fix flaky test
failures:

---- db::inode::tests::schema_internals::test_cannot_change_dir_immutables stdout ----
thread 'db::inode::tests::schema_internals::test_cannot_change_dir_immutables' panicked at 'assertion failed: `(left == right)`
  left: `"error returned from database: could not serialize access due to concurrent update"`,
 right: `"error returned from database: cannot change id or birth_*"`', src/db/inode.rs:740:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    db::inode::tests::schema_internals::test_cannot_change_dir_immutables

test result: FAILED. 85 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.89s

error: test failed, to rerun pass '--lib'