Fix two erroneous implementations of tokio::io::AsyncRead poll_ready
When Poll::Pending, the existing `buf` is not cleared; it still has the last read; we need to check for that instead of blindly using `buf`.

The mis-implementation in ByteCountingReader didn't have any known symptoms.

The mis-implementation in Blake3HashingReader would cause add_storages to fail to add a fofs storage about half the time:

Error: while adding fofs storage, content had
b3sum=Hash("642a9113622619f14b7102a80c3f81c32a083da01c933a408476e264b381b0e9") but file has
b3sum=Hash("6e04337c14222a9a31731faf224e7e906c142b26ba17e325b1983ee93daabc8f")

This was confirmed to be caused by the last read being hashed twice:

$ ls -l
total 40,960
-rw-r----- 1 at at 19,245 2023-04-07 10:03 305642430
-rw-r----- 1 at at  8,192 2023-04-07 10:05 part1
-rw-r----- 1 at at  8,192 2023-04-07 10:05 part2
-rw-r----- 1 at at  2,861 2023-04-07 10:05 part3

$ cat part1 part2 part3 part3 | b3sum
642a9113622619f14b7102a80c3f81c32a083da01c933a408476e264b381b0e9  -